### ISSUE TITLE
License

### ISSUE THREAD

**Issue by tveitocc** [ayoy/upython-aq-monitor#2]
Hello.

In the DS3231 file you state you modified this project: https://github.com/peterhinch/micropython-samples/tree/master/DS3231. This project does have the MIT license and you can find this her:
https://github.com/peterhinch/micropython-samples/blob/master/LICENSE
You will need to add this to your repository to be allowed to redistribute the code.

Just a friendly warning and I have nothing to do with the original project =)

**Comment by ayoy** [comment]
Good catch, fixed it just now. Thanks a lot for pointing this out!
